Debug Build Logs (AFTER build)

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -50,14 +50,19 @@ jobs:
         run: |
           echo "Searching for JsonToolboxWebApp.fsproj..."
           find . -name "JsonToolboxWebApp.fsproj"
-      - name: Debug Build Logs
-        run: |
-            ls -l bin/Debug
-            cat bin/Debug/build.log || echo "No build log found"
+
       # Projekt buildelése WebSharper-rel (.NET)
       - name: Build Project with WebSharper
         run: timeout 300 dotnet ws build --project JsonToolboxWebApp.fsproj 
-
+      - name: Debug Build Logs (AFTER build)
+        run: |
+            if [ -d "bin/Debug" ]; then
+            ls -l bin/Debug
+            cat bin/Debug/build.log || echo "No build log found"
+            else
+            echo "Debug directory not found! Build might have failed."
+            #  exit 1
+            fi
       # WebSharper JavaScript fájlok másolása, ha léteznek
       - name: Copy WebSharper scripts to dist/
         run: |
